namespace UpdateHub.Web.Localization;

/// <summary>
/// In-memory translation dictionaries. Keys are dot-separated namespaces
/// (e.g. "nav.dashboard"); missing keys fall back to the key itself so a
/// missing translation is visible without crashing the page.
/// </summary>
public static class UiStrings
{
    public static readonly IReadOnlyList<(string Code, string Label)> Languages =
    [
        ("en", "EN"),
        ("cs", "CS"),
        ("de", "DE"),
    ];

    public static readonly Dictionary<string, Dictionary<string, string>> Resources = new()
    {
        ["en"] = new()
        {
            // Navigation
            ["nav.dashboard"]     = "Dashboard",
            ["nav.applications"]  = "Applications",
            ["nav.users"]         = "Users",
            ["nav.settings"]      = "Settings",
            ["nav.security"]      = "Security",
            ["nav.audit"]         = "Audit Log",
            ["nav.account"]       = "My Account",
            ["nav.logout"]        = "Logout",
            ["nav.theme"]         = "Theme",
            ["nav.language"]      = "Language",
            ["nav.theme.auto"]    = "Auto",
            ["nav.theme.light"]   = "Light",
            ["nav.theme.dark"]    = "Dark",

            // Roles
            ["role.Admin"]        = "Admin",
            ["role.Manager"]      = "Manager",
            ["role.Viewer"]       = "Viewer",

            // Change password (forced flow)
            ["changepw.title"]    = "Change password",
            ["changepw.prompt"]   = "Your password must be changed before you can continue.",
            ["changepw.current"]  = "Current password",
            ["changepw.new"]      = "New password",
            ["changepw.confirm"]  = "Confirm new password",
            ["changepw.submit"]   = "Save",
            ["changepw.error.missing"]  = "All fields are required.",
            ["changepw.error.mismatch"] = "New password and confirmation do not match.",
            ["changepw.error.invalid"]  = "The current password is incorrect or the new one is too weak.",

            // Users management
            ["users.title"]            = "Users",
            ["users.create"]           = "New user",
            ["users.username"]         = "Username",
            ["users.role"]             = "Role",
            ["users.status"]           = "Status",
            ["users.lastLogin"]        = "Last login",
            ["users.tempPassword"]     = "Temporary password",
            ["users.tempPasswordHint"] = "User will be forced to change this on first login.",
            ["users.generate"]         = "Generate",
            ["users.reset"]            = "Reset password",
            ["users.reset.hint"]       = "Sets a new temporary password and forces the user to change it on next login.",
            ["users.disable"]          = "Disable",
            ["users.enable"]           = "Enable",
            ["users.active"]           = "Active",
            ["users.disabled"]         = "Disabled",
            ["users.pendingPwChange"]  = "Pending password change",
            ["users.you"]              = "You",
            ["users.copyNow.title"]    = "Temporary password — copy now",
            ["users.copyNow.hint"]     = "This is the only time it will be shown. Share it with the user via a secure channel.",
            ["users.email"]            = "Email",
            ["users.email.hint"]       = "Optional — used only to notify the user when their account is created or their password is reset (the password itself is never sent by email).",
            ["users.email.edit"]       = "Edit email",

            // Account page
            ["account.title"]            = "My Account",
            ["account.password"]         = "Change password",
            ["account.password.saved"]   = "Password changed successfully.",
            ["account.totp"]             = "Two-Factor Authentication (TOTP)",
            ["account.totp.hint"]        = "Use any TOTP authenticator app (Google Authenticator, Authy, 1Password, etc.).",
            ["account.totp.enabled"]     = "2FA is enabled",
            ["account.totp.disabled"]    = "2FA is disabled",
            ["account.totp.enable"]      = "Enable 2FA",
            ["account.totp.disable"]     = "Disable 2FA",
            ["account.totp.disable.label"]   = "Enter current code to disable 2FA",
            ["account.totp.disable.confirm"] = "Confirm disable",
            ["account.totp.scanHint"]    = "Scan this URI in your authenticator app or enter the secret manually:",
            ["account.totp.manualKey"]   = "Manual entry key",
            ["account.totp.confirm.label"] = "Enter the 6-digit code to confirm setup",
            ["account.totp.activate"]    = "Activate 2FA",
            ["account.totp.code.required"] = "Enter the 6-digit code from your authenticator.",
            ["account.preferences"]      = "Preferences",
            ["account.theme.hint"]       = "Auto follows your operating system.",
            ["account.language.hint"]    = "UI language for this browser.",

            // Login
            ["login.title"]       = "Sign in",
            ["login.username"]    = "Username",
            ["login.password"]    = "Password",
            ["login.submit"]      = "Sign in",
            ["login.invalid"]     = "Invalid username or password.",
            ["login.blocked"]     = "Your IP address has been blocked due to too many failed login attempts. Contact the administrator.",
            ["login.totp.title"]  = "Two-factor verification",
            ["login.totp.prompt"] = "Enter the 6-digit code from your authenticator app.",
            ["login.totp.code"]   = "Code",
            ["login.totp.submit"] = "Verify",
            ["login.totp.invalid"]= "Code is invalid or expired.",
            ["login.forgot"]      = "Forgot your password?",
            ["login.reset.success"] = "Password has been reset. You can now sign in.",
            ["forgot.title"]      = "Reset password",
            ["forgot.prompt"]     = "Enter your username or email. If a matching account exists, a reset link will be sent to its registered email.",
            ["forgot.who"]        = "Username or email",
            ["forgot.submit"]     = "Send reset link",
            ["forgot.sent"]       = "If the account exists, a reset link has been sent. Check your email and follow the link within 30 minutes.",
            ["forgot.backToLogin"]= "Back to sign in",
            ["reset.title"]       = "Choose a new password",
            ["reset.prompt"]      = "Enter your new password below.",
            ["reset.submit"]      = "Save new password",
            ["reset.error.missingToken"] = "Reset link is missing or invalid. Request a new one.",
            ["reset.error.invalid"] = "The reset link is invalid or has expired. Request a new one.",

            // Dashboard
            ["dashboard.title"]              = "Dashboard",
            ["dashboard.stat.applications"]  = "Applications",
            ["dashboard.stat.published"]     = "Published Releases",
            ["dashboard.stat.downloads"]     = "Total Downloads",
            ["dashboard.applications"]       = "Applications",
            ["dashboard.viewAll"]            = "View all",
            ["dashboard.col.name"]           = "Name",
            ["dashboard.col.slug"]           = "Slug",
            ["dashboard.col.latest"]         = "Latest (Stable)",
            ["dashboard.col.releases"]       = "Releases",
            ["dashboard.empty"]              = "No applications yet.",
            ["dashboard.empty.cta"]          = "Register your first app",
            ["dashboard.manage"]             = "Manage",

            // Common buttons / labels
            ["common.save"]       = "Save",
            ["common.cancel"]     = "Cancel",
            ["common.delete"]     = "Delete",
            ["common.edit"]       = "Edit",
            ["common.create"]     = "Create",
            ["common.publish"]    = "Publish",
            ["common.archive"]    = "Archive",
            ["common.copy"]       = "Copy",
            ["common.copied"]     = "Copied!",
            ["common.confirm"]    = "Confirm",
            ["common.loading"]    = "Loading…",
            ["common.refresh"]    = "Refresh",
            ["common.deleteYes"]  = "Yes, delete",
            ["common.name"]       = "Name",
            ["common.description"]= "Description",
            ["common.upload"]     = "Upload",

            // Page titles
            ["page.settings"]     = "Settings",
            ["page.security"]     = "Security",
            ["page.audit"]        = "Audit Log",
            ["page.apps"]         = "Applications",

            // Settings page (admin)
            ["settings.ciToken"]          = "CI Upload Token",
            ["settings.ciToken.hint"]     = "Used in GitHub Actions as the X-UpdateHub-Token header. Rotating generates a new token — update your CI secrets afterwards.",
            ["settings.reveal"]           = "Reveal",
            ["settings.rotate"]           = "Rotate token",
            ["settings.rotateConfirm"]    = "Rotate and invalidate the current token?",
            ["settings.rotateYes"]        = "Yes, rotate",
            ["settings.rotatedMsg"]       = "Token rotated — update your CI secrets with the new value above.",
            ["settings.smtp"]             = "Email (SMTP)",
            ["settings.smtp.hint"]        = "Edit SMTP credentials at runtime — the values are persisted to the database (password is encrypted at rest).",
            ["settings.smtp.envHint"]     = "Currently using values from environment variables / appsettings — fill the form to override.",
            ["settings.smtp.host"]        = "Host",
            ["settings.smtp.port"]        = "Port",
            ["settings.smtp.from"]        = "From address",
            ["settings.smtp.username"]    = "Username",
            ["settings.smtp.password"]    = "Password",
            ["settings.smtp.password.stored"]     = "stored",
            ["settings.smtp.password.placeholder"]= "leave empty to keep stored password",
            ["settings.smtp.password.willClear"]  = "Stored password will be cleared on save.",
            ["settings.smtp.password.clear"]      = "Clear stored password",
            ["settings.smtp.to"]          = "Recipient (To)",
            ["settings.smtp.sendTest"]    = "Send test email",
            ["settings.smtp.sending"]     = "Sending…",
            ["settings.smtp.saved"]       = "SMTP settings saved.",
            ["settings.smtp.testSent"]    = "Test email queued (check your inbox if SMTP is configured).",

            // Navigation user info
            ["nav.signedInAs"]            = "Signed in as",
            ["nav.user"]                  = "User",
            ["nav.role"]                  = "Role",
            ["nav.search"]                = "Search apps…",
            ["nav.analytics"]             = "Analytics",
            ["nav.storage"]               = "Storage",
            ["dashboard.recent"]          = "Recent activity",
            ["analytics.title"]           = "Analytics",
            ["analytics.window.7"]        = "Last 7 days",
            ["analytics.window.30"]       = "Last 30 days",
            ["analytics.window.90"]       = "Last 90 days",
            ["analytics.totalDownloads"]  = "Total downloads",
            ["analytics.activeDays"]      = "Active days",
            ["analytics.avgPerDay"]       = "Avg / day",
            ["analytics.perDay"]          = "Downloads per day",
            ["analytics.byPlatform"]      = "By platform",
            ["analytics.topVersions"]     = "Top versions",
            ["analytics.noData"]          = "No data for this window.",
            ["storage.title"]             = "Storage",
            ["storage.totalOnDisk"]       = "Total on disk",
            ["storage.totalInDb"]         = "Tracked artifacts",
            ["storage.artifactCount"]     = "Artifact count",
            ["storage.byApp"]             = "By application",
            ["storage.size"]              = "Size",
            ["storage.share"]             = "Share",
            ["storage.empty"]             = "No artifacts stored yet.",
            ["storage.cleanup"]           = "Cleanup",
            ["storage.cleanup.hint"]      = "Permanently delete artifact files attached to releases archived longer than the chosen window. Release metadata is kept.",
            ["storage.cleanup.olderThan"] = "Archived older than",
            ["storage.cleanup.run"]       = "Run cleanup",
            ["storage.days"]              = "days",
            ["releases.dropHint"]         = "Drop a file here or click to choose",
            ["users.edit"]                = "Edit user",
            ["users.forceChangePw"]       = "Force the user to change their password on next login",
            ["users.forceChangePw.self"]  = "You cannot force a password change on your own account.",
            ["apps.appToken.rotated"]     = "rotated",
            ["apps.appToken.rotated.today"] = "today",
            ["settings.webhook"]          = "Webhook signing",
            ["settings.webhook.hint"]     = "Outgoing publish webhooks are signed with an HMAC-SHA256 header (X-UpdateHub-Signature) so the receiver can verify the request comes from your server. Rotating invalidates the previous secret immediately.",
            ["settings.webhook.generate"] = "Generate secret",
            ["settings.webhook.rotate"]   = "Rotate secret",
            ["settings.webhook.rotated"]  = "Webhook secret rotated. Update any verifying receivers.",
            ["settings.webhook.cleared"]  = "Webhook secret cleared — outgoing webhooks will no longer be signed.",
            ["account.tokens"]            = "Personal access tokens",
            ["account.tokens.hint"]       = "Long-lived bearer tokens you can use with the CLI / scripts to upload artifacts on your behalf. Each token is shown only once — copy it immediately.",
            ["account.tokens.name"]       = "Label",
            ["account.tokens.expiry"]     = "Expires in",
            ["account.tokens.expiry.never"] = "Never",
            ["account.tokens.create"]     = "Create token",
            ["account.tokens.shown"]      = "Copy now (shown only once)",
            ["account.tokens.prefix"]     = "Prefix",
            ["account.tokens.expires"]    = "Expires",
            ["account.tokens.revoke"]     = "Revoke",
            ["account.tokens.revoked"]    = "Revoked",
            ["account.tokens.expired"]    = "Expired",
            ["account.sessions"]          = "Active sessions",
            ["account.sessions.hint"]     = "Sign out of all browsers and devices using this account — useful if you suspect a session was compromised. You will need to sign in again here.",
            ["account.sessions.revokeAll"] = "Sign out everywhere",
            ["account.sessions.revoked"]   = "All sessions invalidated. You will be signed out shortly.",
            ["account.totp.backupCodes.remaining"]    = "Backup codes remaining",
            ["account.totp.backupCodes.regenerate"]   = "Regenerate codes",
            ["account.totp.backupCodes.lowWarning"]   = "You have very few backup codes left — regenerate to get a fresh set.",
            ["account.totp.backupCodes.shownOnce"]    = "New backup codes — store these somewhere safe",
            ["account.totp.backupCodes.shownOnce.hint"] = "Each code works once and substitutes for an authenticator code if you lose your device. Codes will not be shown again.",
            ["apps.webhookUrl"]            = "Per-app webhook URL",
            ["apps.webhookUrl.hint"]       = "(optional — overrides the global publish webhook for this app)",
            ["settings.backup"]            = "Backup",
            ["settings.backup.hint"]       = "Download a ZIP containing the SQLite database and the data-protection key ring. Artifact files are not included — back those up separately at the volume level.",
            ["settings.backup.download"]   = "Download backup",

            // Apps list
            ["apps.new"]                  = "New application",
            ["apps.empty"]                = "No applications registered yet.",
            ["apps.col.created"]          = "Created",
            ["apps.slug"]                 = "Slug",
            ["apps.slug.hint"]            = "(unique ID used in API calls, e.g. my-app)",
            ["apps.descriptionOptional"]  = "Description (optional)",
            ["apps.err.slugRequired"]     = "Slug is required.",
            ["apps.err.nameRequired"]     = "Name is required.",
            ["apps.err.slugExists"]       = "Slug already exists.",

            // App detail
            ["apps.delete"]               = "Delete application",
            ["apps.edit"]                 = "Edit application",
            ["apps.appToken"]             = "Per-app CI token",
            ["apps.appToken.custom"]      = "Custom token active — overrides the global token",
            ["apps.appToken.global"]      = "Using the global CI token",
            ["apps.appToken.generate"]    = "Generate token",
            ["apps.appToken.rotate"]      = "Rotate",
            ["apps.appToken.remove"]      = "Remove",
            ["apps.appToken.reveal"]      = "Reveal",
            ["apps.appToken.hide"]        = "Hide",
            ["apps.apiEndpoints"]         = "API endpoints",
            ["apps.releases"]             = "Releases",
            ["apps.newRelease"]           = "New release",
            ["apps.releases.empty"]       = "No releases yet.",
            ["apps.delete.confirm"]       = "Delete application?",
            ["apps.delete.warn"]          = "This will permanently delete the app and all its releases and artifacts.",

            // Releases
            ["releases.version"]          = "Version",
            ["releases.channel"]          = "Channel",
            ["releases.status"]           = "Status",
            ["releases.notes"]            = "Release notes",
            ["releases.notesPlaceholder"] = "What changed in this version…",
            ["releases.mandatory"]        = "Mandatory update",
            ["releases.published"]        = "Published",
            ["releases.artifacts"]        = "Artifacts",
            ["releases.col.platform"]     = "Platform",
            ["releases.col.arch"]         = "Architecture",
            ["releases.col.file"]         = "File",
            ["releases.col.size"]         = "Size",
            ["releases.col.signature"]    = "Signature",
            ["releases.col.downloads"]    = "Downloads",
            ["releases.upload"]           = "Upload artifact",
            ["releases.signature"]        = "Tauri Ed25519 signature",
            ["releases.signature.hint"]   = "(only needed for Tauri apps)",
            ["releases.signaturePlaceholder"] = "paste signature from tauri signer…",
            ["releases.file"]             = "File",
            ["releases.uploading"]        = "Uploading, please wait…",
            ["releases.err.version"]      = "Version is required.",
            ["releases.delete.confirm"]   = "Delete release?",
            ["releases.delete.warn"]      = "All artifacts will also be deleted permanently.",
            ["releases.empty"]            = "No artifacts uploaded yet.",
            ["releases.manage"]           = "Manage →",
            ["releases.status.draft"]     = "Draft",
            ["releases.status.published"] = "Published",
            ["releases.status.archived"]  = "Archived",
            ["releases.channel.stable"]   = "Stable",
            ["releases.channel.beta"]     = "Beta",
            ["releases.channel.alpha"]    = "Alpha",
            ["releases.mandatoryBadge"]   = "Mandatory",
            ["releases.minFromVersion"]   = "Minimum version to upgrade from",
            ["releases.minFromVersion.hint"]  = "(optional — clients on a lower version are stepped through an intermediate release)",
            ["releases.minFromVersion.none"]  = "any",
            ["releases.minFromVersion.badge"] = "≥",

            // Security page
            ["security.blockedIps"]       = "Blocked IPs",
            ["security.suspiciousIps"]    = "Suspicious IPs",
            ["security.threshold"]        = "Auto-block threshold",
            ["security.loginAttempts"]    = "Login attempts",
            ["security.filterIp"]         = "Filter by IP…",
            ["security.blockManual"]      = "+ Block IP manually…",
            ["security.blockThis"]        = "Block this IP",
            ["security.col.ip"]           = "IP address",
            ["security.col.status"]       = "Status",
            ["security.col.failed"]       = "Failed",
            ["security.col.firstSeen"]    = "First seen",
            ["security.col.lastAttempt"]  = "Last attempt",
            ["security.col.unblockedAt"] = "Unblocked at",
            ["security.col.userAgent"]    = "User agent",
            ["security.empty"]            = "No login attempts recorded yet.",
            ["security.unblock"]          = "Unblock",
            ["security.block"]            = "Block",
            ["security.removeRecord"]     = "Remove record",
            ["security.status.blocked"]   = "Blocked",
            ["security.status.blocked.manual"] = "Blocked (manual)",
            ["security.status.blocked.auto"]   = "Blocked (auto)",
            ["security.status.suspicious"]= "Suspicious",
            ["security.status.ok"]        = "OK",
        },

        ["cs"] = new()
        {
            // Navigation
            ["nav.dashboard"]     = "Přehled",
            ["nav.applications"]  = "Aplikace",
            ["nav.users"]         = "Uživatelé",
            ["nav.settings"]      = "Nastavení",
            ["nav.security"]      = "Zabezpečení",
            ["nav.audit"]         = "Audit",
            ["nav.account"]       = "Můj účet",
            ["nav.logout"]        = "Odhlásit",
            ["nav.theme"]         = "Vzhled",
            ["nav.language"]      = "Jazyk",
            ["nav.theme.auto"]    = "Auto",
            ["nav.theme.light"]   = "Světlý",
            ["nav.theme.dark"]    = "Tmavý",

            // Roles
            ["role.Admin"]        = "Admin",
            ["role.Manager"]      = "Manažer",
            ["role.Viewer"]       = "Prohlížeč",

            // Change password (forced flow)
            ["changepw.title"]    = "Změna hesla",
            ["changepw.prompt"]   = "Před pokračováním si musíte změnit heslo.",
            ["changepw.current"]  = "Současné heslo",
            ["changepw.new"]      = "Nové heslo",
            ["changepw.confirm"]  = "Potvrzení nového hesla",
            ["changepw.submit"]   = "Uložit",
            ["changepw.error.missing"]  = "Všechna pole jsou povinná.",
            ["changepw.error.mismatch"] = "Nové heslo a potvrzení se neshodují.",
            ["changepw.error.invalid"]  = "Současné heslo není správné nebo je nové heslo příliš slabé.",

            // Users management
            ["users.title"]            = "Uživatelé",
            ["users.create"]           = "Nový uživatel",
            ["users.username"]         = "Uživatelské jméno",
            ["users.role"]             = "Role",
            ["users.status"]           = "Stav",
            ["users.lastLogin"]        = "Poslední přihlášení",
            ["users.tempPassword"]     = "Dočasné heslo",
            ["users.tempPasswordHint"] = "Uživatel bude při prvním přihlášení nucen heslo změnit.",
            ["users.generate"]         = "Vygenerovat",
            ["users.reset"]            = "Resetovat heslo",
            ["users.reset.hint"]       = "Nastaví nové dočasné heslo a uživatel bude při příštím přihlášení nucen ho změnit.",
            ["users.disable"]          = "Deaktivovat",
            ["users.enable"]           = "Aktivovat",
            ["users.active"]           = "Aktivní",
            ["users.disabled"]         = "Deaktivovaný",
            ["users.pendingPwChange"]  = "Čeká na změnu hesla",
            ["users.you"]              = "Vy",
            ["users.copyNow.title"]    = "Dočasné heslo — zkopírovat hned",
            ["users.copyNow.hint"]     = "Heslo se zobrazí pouze jednou. Předejte ho uživateli bezpečným kanálem.",
            ["users.email"]            = "Email",
            ["users.email.hint"]       = "Volitelné — použije se pouze pro upozornění uživatele o vytvoření účtu nebo resetu hesla (samotné heslo se emailem nikdy neposílá).",
            ["users.email.edit"]       = "Upravit email",

            // Account page
            ["account.title"]            = "Můj účet",
            ["account.password"]         = "Změna hesla",
            ["account.password.saved"]   = "Heslo bylo úspěšně změněno.",
            ["account.totp"]             = "Dvoufaktorové ověření (TOTP)",
            ["account.totp.hint"]        = "Použijte libovolnou TOTP aplikaci (Google Authenticator, Authy, 1Password atd.).",
            ["account.totp.enabled"]     = "2FA je zapnuté",
            ["account.totp.disabled"]    = "2FA je vypnuté",
            ["account.totp.enable"]      = "Zapnout 2FA",
            ["account.totp.disable"]     = "Vypnout 2FA",
            ["account.totp.disable.label"]   = "Pro vypnutí 2FA zadejte aktuální kód",
            ["account.totp.disable.confirm"] = "Potvrdit vypnutí",
            ["account.totp.scanHint"]    = "Naskenujte URI v autentifikační aplikaci nebo zadejte tajný klíč ručně:",
            ["account.totp.manualKey"]   = "Klíč pro ruční zadání",
            ["account.totp.confirm.label"] = "Pro potvrzení nastavení zadejte 6místný kód",
            ["account.totp.activate"]    = "Aktivovat 2FA",
            ["account.totp.code.required"] = "Zadejte 6místný kód z autentifikační aplikace.",
            ["account.preferences"]      = "Preference",
            ["account.theme.hint"]       = "Auto se řídí nastavením operačního systému.",
            ["account.language.hint"]    = "Jazyk rozhraní pro tento prohlížeč.",

            // Login
            ["login.title"]       = "Přihlášení",
            ["login.username"]    = "Uživatelské jméno",
            ["login.password"]    = "Heslo",
            ["login.submit"]      = "Přihlásit se",
            ["login.invalid"]     = "Neplatné jméno nebo heslo.",
            ["login.blocked"]     = "Vaše IP adresa byla zablokována kvůli příliš mnoha neúspěšným pokusům o přihlášení. Kontaktujte správce.",
            ["login.totp.title"]  = "Dvoufaktorové ověření",
            ["login.totp.prompt"] = "Zadejte 6místný kód z autentifikační aplikace.",
            ["login.totp.code"]   = "Kód",
            ["login.totp.submit"] = "Ověřit",
            ["login.totp.invalid"]= "Kód je neplatný nebo vypršel.",
            ["login.forgot"]      = "Zapomněli jste heslo?",
            ["login.reset.success"] = "Heslo bylo resetováno. Můžete se přihlásit.",
            ["forgot.title"]      = "Reset hesla",
            ["forgot.prompt"]     = "Zadejte uživatelské jméno nebo email. Pokud účet existuje, na registrovaný email se odešle odkaz pro reset.",
            ["forgot.who"]        = "Uživatelské jméno nebo email",
            ["forgot.submit"]     = "Odeslat odkaz",
            ["forgot.sent"]       = "Pokud účet existuje, odkaz pro reset byl odeslán. Zkontrolujte email a klikněte na odkaz do 30 minut.",
            ["forgot.backToLogin"]= "Zpět na přihlášení",
            ["reset.title"]       = "Zvolte nové heslo",
            ["reset.prompt"]      = "Zadejte nové heslo.",
            ["reset.submit"]      = "Uložit nové heslo",
            ["reset.error.missingToken"] = "Odkaz pro reset chybí nebo je neplatný. Vyžádejte si nový.",
            ["reset.error.invalid"] = "Odkaz pro reset je neplatný nebo vypršel. Vyžádejte si nový.",

            // Dashboard
            ["dashboard.title"]              = "Přehled",
            ["dashboard.stat.applications"]  = "Aplikace",
            ["dashboard.stat.published"]     = "Publikované verze",
            ["dashboard.stat.downloads"]     = "Celkem stažení",
            ["dashboard.applications"]       = "Aplikace",
            ["dashboard.viewAll"]            = "Zobrazit vše",
            ["dashboard.col.name"]           = "Název",
            ["dashboard.col.slug"]           = "Identifikátor",
            ["dashboard.col.latest"]         = "Nejnovější (Stable)",
            ["dashboard.col.releases"]       = "Verze",
            ["dashboard.empty"]              = "Žádné aplikace.",
            ["dashboard.empty.cta"]          = "Zaregistrovat první aplikaci",
            ["dashboard.manage"]             = "Spravovat",

            // Common
            ["common.save"]       = "Uložit",
            ["common.cancel"]     = "Zrušit",
            ["common.delete"]     = "Smazat",
            ["common.edit"]       = "Upravit",
            ["common.create"]     = "Vytvořit",
            ["common.publish"]    = "Publikovat",
            ["common.archive"]    = "Archivovat",
            ["common.copy"]       = "Kopírovat",
            ["common.copied"]     = "Zkopírováno!",
            ["common.confirm"]    = "Potvrdit",
            ["common.loading"]    = "Načítání…",
            ["common.refresh"]    = "Obnovit",
            ["common.deleteYes"]  = "Ano, smazat",
            ["common.name"]       = "Název",
            ["common.description"]= "Popis",
            ["common.upload"]     = "Nahrát",

            // Page titles
            ["page.settings"]     = "Nastavení",
            ["page.security"]     = "Zabezpečení",
            ["page.audit"]        = "Audit log",
            ["page.apps"]         = "Aplikace",

            // Settings page (admin)
            ["settings.ciToken"]          = "CI nahrávací token",
            ["settings.ciToken.hint"]     = "Používá se v GitHub Actions jako hlavička X-UpdateHub-Token. Rotace vygeneruje nový token — pak aktualizujte CI secrets.",
            ["settings.reveal"]           = "Odhalit",
            ["settings.rotate"]           = "Rotovat token",
            ["settings.rotateConfirm"]    = "Rotovat a zneplatnit současný token?",
            ["settings.rotateYes"]        = "Ano, rotovat",
            ["settings.rotatedMsg"]       = "Token byl rotován — aktualizujte CI secrets hodnotou výše.",
            ["settings.smtp"]             = "Email (SMTP)",
            ["settings.smtp.hint"]        = "Upravit SMTP přihlašovací údaje za běhu — hodnoty se ukládají do databáze (heslo šifrované).",
            ["settings.smtp.envHint"]     = "Nyní se používají hodnoty z proměnných prostředí / appsettings — vyplňte formulář pro přepsání.",
            ["settings.smtp.host"]        = "Host",
            ["settings.smtp.port"]        = "Port",
            ["settings.smtp.from"]        = "Adresa odesílatele",
            ["settings.smtp.username"]    = "Uživatelské jméno",
            ["settings.smtp.password"]    = "Heslo",
            ["settings.smtp.password.stored"]     = "uloženo",
            ["settings.smtp.password.placeholder"]= "ponechte prázdné pro zachování uloženého hesla",
            ["settings.smtp.password.willClear"]  = "Uložené heslo bude při uložení smazáno.",
            ["settings.smtp.password.clear"]      = "Smazat uložené heslo",
            ["settings.smtp.to"]          = "Příjemce (To)",
            ["settings.smtp.sendTest"]    = "Odeslat zkušební email",
            ["settings.smtp.sending"]     = "Odesílá se…",
            ["settings.smtp.saved"]       = "SMTP nastavení uloženo.",
            ["settings.smtp.testSent"]    = "Zkušební email byl zařazen do fronty (zkontrolujte schránku, pokud je SMTP nastaveno).",

            // Navigation user info
            ["nav.signedInAs"]            = "Přihlášený jako",
            ["nav.user"]                  = "Uživatel",
            ["nav.role"]                  = "Role",
            ["nav.search"]                = "Hledat aplikace…",
            ["nav.analytics"]             = "Statistiky",
            ["nav.storage"]               = "Úložiště",
            ["dashboard.recent"]          = "Poslední aktivita",
            ["analytics.title"]           = "Statistiky",
            ["analytics.window.7"]        = "Posledních 7 dnů",
            ["analytics.window.30"]       = "Posledních 30 dnů",
            ["analytics.window.90"]       = "Posledních 90 dnů",
            ["analytics.totalDownloads"]  = "Celkem stažení",
            ["analytics.activeDays"]      = "Aktivní dny",
            ["analytics.avgPerDay"]       = "Průměr / den",
            ["analytics.perDay"]          = "Stažení za den",
            ["analytics.byPlatform"]      = "Podle platformy",
            ["analytics.topVersions"]     = "Nejstahovanější verze",
            ["analytics.noData"]          = "Pro toto období žádná data.",
            ["storage.title"]             = "Úložiště",
            ["storage.totalOnDisk"]       = "Celkem na disku",
            ["storage.totalInDb"]         = "Evidované artefakty",
            ["storage.artifactCount"]     = "Počet artefaktů",
            ["storage.byApp"]             = "Podle aplikace",
            ["storage.size"]              = "Velikost",
            ["storage.share"]             = "Podíl",
            ["storage.empty"]             = "Žádné uložené artefakty.",
            ["storage.cleanup"]           = "Úklid",
            ["storage.cleanup.hint"]      = "Trvale smaže soubory artefaktů u verzí archivovaných déle než vybrané období. Metadata verzí zůstávají.",
            ["storage.cleanup.olderThan"] = "Archivováno déle než",
            ["storage.cleanup.run"]       = "Spustit úklid",
            ["storage.days"]              = "dnů",
            ["releases.dropHint"]         = "Přetáhněte sem soubor nebo klikněte pro výběr",
            ["users.edit"]                = "Upravit uživatele",
            ["users.forceChangePw"]       = "Vynutit změnu hesla při dalším přihlášení",
            ["users.forceChangePw.self"]  = "Nemůžete vynutit změnu hesla u vlastního účtu.",
            ["apps.appToken.rotated"]     = "rotováno",
            ["apps.appToken.rotated.today"] = "dnes",
            ["settings.webhook"]          = "Podepisování webhooků",
            ["settings.webhook.hint"]     = "Odchozí webhooky o publikaci jsou podepsány HMAC-SHA256 hlavičkou (X-UpdateHub-Signature), aby si příjemce mohl ověřit původ. Rotace okamžitě zneplatní předchozí klíč.",
            ["settings.webhook.generate"] = "Vygenerovat klíč",
            ["settings.webhook.rotate"]   = "Rotovat klíč",
            ["settings.webhook.rotated"]  = "Klíč rotován. Aktualizujte všechny příjemce, kteří ho ověřují.",
            ["settings.webhook.cleared"]  = "Klíč smazán — odchozí webhooky už nebudou podepsané.",
            ["account.tokens"]            = "Osobní přístupové tokeny",
            ["account.tokens.hint"]       = "Dlouhodobé bearer tokeny pro CLI / skripty, které pod vaším jménem nahrávají artefakty. Každý token se zobrazí pouze jednou — okamžitě si ho zkopírujte.",
            ["account.tokens.name"]       = "Popisek",
            ["account.tokens.expiry"]     = "Expirace",
            ["account.tokens.expiry.never"] = "Nikdy",
            ["account.tokens.create"]     = "Vytvořit token",
            ["account.tokens.shown"]      = "Zkopírujte hned (zobrazeno pouze jednou)",
            ["account.tokens.prefix"]     = "Prefix",
            ["account.tokens.expires"]    = "Expiruje",
            ["account.tokens.revoke"]     = "Zneplatnit",
            ["account.tokens.revoked"]    = "Zneplatněn",
            ["account.tokens.expired"]    = "Vypršel",
            ["account.sessions"]          = "Aktivní relace",
            ["account.sessions.hint"]     = "Odhlásit ze všech prohlížečů a zařízení používajících tento účet — užitečné, pokud máte podezření na kompromitaci. Zde se budete muset znovu přihlásit.",
            ["account.sessions.revokeAll"] = "Odhlásit všude",
            ["account.sessions.revoked"]   = "Všechny relace zneplatněny. Brzy budete odhlášeni.",
            ["account.totp.backupCodes.remaining"]    = "Zbývající záložní kódy",
            ["account.totp.backupCodes.regenerate"]   = "Vygenerovat nové kódy",
            ["account.totp.backupCodes.lowWarning"]   = "Zbývá vám velmi málo záložních kódů — vygenerujte si nové.",
            ["account.totp.backupCodes.shownOnce"]    = "Nové záložní kódy — uložte si je bezpečně",
            ["account.totp.backupCodes.shownOnce.hint"] = "Každý kód lze použít jen jednou a nahrazuje kód z autentifikátoru, pokud zařízení ztratíte. Kódy se už nezobrazí znovu.",
            ["apps.webhookUrl"]            = "Webhook URL pro aplikaci",
            ["apps.webhookUrl.hint"]       = "(volitelné — pro tuto aplikaci přepíše globální webhook)",
            ["settings.backup"]            = "Záloha",
            ["settings.backup.hint"]       = "Stáhne ZIP s SQLite databází a klíči Data Protection. Soubory artefaktů zahrnuté nejsou — ty zálohujte samostatně na úrovni volume.",
            ["settings.backup.download"]   = "Stáhnout zálohu",

            // Apps list
            ["apps.new"]                  = "Nová aplikace",
            ["apps.empty"]                = "Zatím nejsou registrované žádné aplikace.",
            ["apps.col.created"]          = "Vytvořeno",
            ["apps.slug"]                 = "Identifikátor",
            ["apps.slug.hint"]            = "(unikátní ID pro API volání, např. moje-aplikace)",
            ["apps.descriptionOptional"]  = "Popis (volitelně)",
            ["apps.err.slugRequired"]     = "Identifikátor je povinný.",
            ["apps.err.nameRequired"]     = "Název je povinný.",
            ["apps.err.slugExists"]       = "Identifikátor už existuje.",

            // App detail
            ["apps.delete"]               = "Smazat aplikaci",
            ["apps.edit"]                 = "Upravit aplikaci",
            ["apps.appToken"]             = "CI token aplikace",
            ["apps.appToken.custom"]      = "Vlastní token aktivní — přepisuje globální",
            ["apps.appToken.global"]      = "Používá se globální CI token",
            ["apps.appToken.generate"]    = "Vygenerovat token",
            ["apps.appToken.rotate"]      = "Rotovat",
            ["apps.appToken.remove"]      = "Odstranit",
            ["apps.appToken.reveal"]      = "Odhalit",
            ["apps.appToken.hide"]        = "Skrýt",
            ["apps.apiEndpoints"]         = "API endpointy",
            ["apps.releases"]             = "Verze",
            ["apps.newRelease"]           = "Nová verze",
            ["apps.releases.empty"]       = "Zatím žádné verze.",
            ["apps.delete.confirm"]       = "Smazat aplikaci?",
            ["apps.delete.warn"]          = "Tímto trvale smažete aplikaci včetně všech verzí a artefaktů.",

            // Releases
            ["releases.version"]          = "Verze",
            ["releases.channel"]          = "Kanál",
            ["releases.status"]           = "Stav",
            ["releases.notes"]            = "Poznámky k verzi",
            ["releases.notesPlaceholder"] = "Co se v této verzi změnilo…",
            ["releases.mandatory"]        = "Povinná aktualizace",
            ["releases.published"]        = "Publikováno",
            ["releases.artifacts"]        = "Artefakty",
            ["releases.col.platform"]     = "Platforma",
            ["releases.col.arch"]         = "Architektura",
            ["releases.col.file"]         = "Soubor",
            ["releases.col.size"]         = "Velikost",
            ["releases.col.signature"]    = "Podpis",
            ["releases.col.downloads"]    = "Stažení",
            ["releases.upload"]           = "Nahrát artefakt",
            ["releases.signature"]        = "Tauri Ed25519 podpis",
            ["releases.signature.hint"]   = "(jen pro Tauri aplikace)",
            ["releases.signaturePlaceholder"] = "vložte podpis z tauri signer…",
            ["releases.file"]             = "Soubor",
            ["releases.uploading"]        = "Nahrávám, počkejte prosím…",
            ["releases.err.version"]      = "Verze je povinná.",
            ["releases.delete.confirm"]   = "Smazat verzi?",
            ["releases.delete.warn"]      = "Trvale se smažou i všechny artefakty.",
            ["releases.empty"]            = "Zatím nebyly nahrány žádné artefakty.",
            ["releases.manage"]           = "Spravovat →",
            ["releases.status.draft"]     = "Koncept",
            ["releases.status.published"] = "Publikováno",
            ["releases.status.archived"]  = "Archivováno",
            ["releases.channel.stable"]   = "Stable",
            ["releases.channel.beta"]     = "Beta",
            ["releases.channel.alpha"]    = "Alpha",
            ["releases.mandatoryBadge"]   = "Povinné",
            ["releases.minFromVersion"]   = "Minimální verze pro přechod",
            ["releases.minFromVersion.hint"]  = "(volitelné — klienti na nižší verzi projdou nejdřív přes mezikrok)",
            ["releases.minFromVersion.none"]  = "jakákoliv",
            ["releases.minFromVersion.badge"] = "≥",

            // Security page
            ["security.blockedIps"]       = "Blokované IP",
            ["security.suspiciousIps"]    = "Podezřelé IP",
            ["security.threshold"]        = "Práh pro automatický blok",
            ["security.loginAttempts"]    = "Pokusy o přihlášení",
            ["security.filterIp"]         = "Filtr podle IP…",
            ["security.blockManual"]      = "+ Ručně zablokovat IP…",
            ["security.blockThis"]        = "Zablokovat tuto IP",
            ["security.col.ip"]           = "IP adresa",
            ["security.col.status"]       = "Stav",
            ["security.col.failed"]       = "Neúspěšné",
            ["security.col.firstSeen"]    = "První pokus",
            ["security.col.lastAttempt"]  = "Poslední pokus",
            ["security.col.unblockedAt"] = "Odblokováno",
            ["security.col.userAgent"]    = "User Agent",
            ["security.empty"]            = "Zatím žádné pokusy o přihlášení.",
            ["security.unblock"]          = "Odblokovat",
            ["security.block"]            = "Zablokovat",
            ["security.removeRecord"]     = "Smazat záznam",
            ["security.status.blocked"]   = "Zablokováno",
            ["security.status.blocked.manual"] = "Zablokováno (ručně)",
            ["security.status.blocked.auto"]   = "Zablokováno (auto)",
            ["security.status.suspicious"]= "Podezřelé",
            ["security.status.ok"]        = "OK",
        },

        ["de"] = new()
        {
            // Navigation
            ["nav.dashboard"]     = "Übersicht",
            ["nav.applications"]  = "Anwendungen",
            ["nav.users"]         = "Benutzer",
            ["nav.settings"]      = "Einstellungen",
            ["nav.security"]      = "Sicherheit",
            ["nav.audit"]         = "Audit-Log",
            ["nav.account"]       = "Mein Konto",
            ["nav.logout"]        = "Abmelden",
            ["nav.theme"]         = "Design",
            ["nav.language"]      = "Sprache",
            ["nav.theme.auto"]    = "Auto",
            ["nav.theme.light"]   = "Hell",
            ["nav.theme.dark"]    = "Dunkel",

            // Roles
            ["role.Admin"]        = "Admin",
            ["role.Manager"]      = "Manager",
            ["role.Viewer"]       = "Betrachter",

            // Change password (forced flow)
            ["changepw.title"]    = "Passwort ändern",
            ["changepw.prompt"]   = "Sie müssen Ihr Passwort ändern, bevor Sie fortfahren können.",
            ["changepw.current"]  = "Aktuelles Passwort",
            ["changepw.new"]      = "Neues Passwort",
            ["changepw.confirm"]  = "Neues Passwort bestätigen",
            ["changepw.submit"]   = "Speichern",
            ["changepw.error.missing"]  = "Alle Felder sind erforderlich.",
            ["changepw.error.mismatch"] = "Neues Passwort und Bestätigung stimmen nicht überein.",
            ["changepw.error.invalid"]  = "Das aktuelle Passwort ist falsch oder das neue Passwort ist zu schwach.",

            // Users management
            ["users.title"]            = "Benutzer",
            ["users.create"]           = "Neuer Benutzer",
            ["users.username"]         = "Benutzername",
            ["users.role"]             = "Rolle",
            ["users.status"]           = "Status",
            ["users.lastLogin"]        = "Letzte Anmeldung",
            ["users.tempPassword"]     = "Temporäres Passwort",
            ["users.tempPasswordHint"] = "Der Benutzer muss dieses bei der ersten Anmeldung ändern.",
            ["users.generate"]         = "Generieren",
            ["users.reset"]            = "Passwort zurücksetzen",
            ["users.reset.hint"]       = "Setzt ein neues temporäres Passwort und zwingt den Benutzer, es bei der nächsten Anmeldung zu ändern.",
            ["users.disable"]          = "Deaktivieren",
            ["users.enable"]           = "Aktivieren",
            ["users.active"]           = "Aktiv",
            ["users.disabled"]         = "Deaktiviert",
            ["users.pendingPwChange"]  = "Passwortwechsel ausstehend",
            ["users.you"]              = "Sie",
            ["users.copyNow.title"]    = "Temporäres Passwort — jetzt kopieren",
            ["users.copyNow.hint"]     = "Wird nur einmal angezeigt. Übermitteln Sie es dem Benutzer über einen sicheren Kanal.",
            ["users.email"]            = "E-Mail",
            ["users.email.hint"]       = "Optional — wird nur verwendet, um den Benutzer über die Kontoerstellung oder einen Passwort-Reset zu benachrichtigen (das Passwort selbst wird niemals per E-Mail gesendet).",
            ["users.email.edit"]       = "E-Mail bearbeiten",

            // Account page
            ["account.title"]            = "Mein Konto",
            ["account.password"]         = "Passwort ändern",
            ["account.password.saved"]   = "Passwort erfolgreich geändert.",
            ["account.totp"]             = "Zwei-Faktor-Authentifizierung (TOTP)",
            ["account.totp.hint"]        = "Verwenden Sie eine beliebige TOTP-App (Google Authenticator, Authy, 1Password usw.).",
            ["account.totp.enabled"]     = "2FA ist aktiviert",
            ["account.totp.disabled"]    = "2FA ist deaktiviert",
            ["account.totp.enable"]      = "2FA aktivieren",
            ["account.totp.disable"]     = "2FA deaktivieren",
            ["account.totp.disable.label"]   = "Geben Sie den aktuellen Code ein, um 2FA zu deaktivieren",
            ["account.totp.disable.confirm"] = "Deaktivieren bestätigen",
            ["account.totp.scanHint"]    = "Scannen Sie diese URI in Ihrer Authenticator-App oder geben Sie den Schlüssel manuell ein:",
            ["account.totp.manualKey"]   = "Manueller Schlüssel",
            ["account.totp.confirm.label"] = "Geben Sie den 6-stelligen Code zur Bestätigung ein",
            ["account.totp.activate"]    = "2FA aktivieren",
            ["account.totp.code.required"] = "Geben Sie den 6-stelligen Code aus Ihrer App ein.",
            ["account.preferences"]      = "Einstellungen",
            ["account.theme.hint"]       = "Auto folgt der Einstellung Ihres Betriebssystems.",
            ["account.language.hint"]    = "Sprache der Oberfläche für diesen Browser.",

            // Login
            ["login.title"]       = "Anmelden",
            ["login.username"]    = "Benutzername",
            ["login.password"]    = "Passwort",
            ["login.submit"]      = "Anmelden",
            ["login.invalid"]     = "Ungültiger Benutzername oder Passwort.",
            ["login.blocked"]     = "Ihre IP-Adresse wurde aufgrund zu vieler fehlgeschlagener Anmeldeversuche gesperrt. Wenden Sie sich an den Administrator.",
            ["login.totp.title"]  = "Zwei-Faktor-Verifizierung",
            ["login.totp.prompt"] = "Geben Sie den 6-stelligen Code aus Ihrer Authenticator-App ein.",
            ["login.totp.code"]   = "Code",
            ["login.totp.submit"] = "Bestätigen",
            ["login.totp.invalid"]= "Code ist ungültig oder abgelaufen.",
            ["login.forgot"]      = "Passwort vergessen?",
            ["login.reset.success"] = "Passwort wurde zurückgesetzt. Sie können sich jetzt anmelden.",
            ["forgot.title"]      = "Passwort zurücksetzen",
            ["forgot.prompt"]     = "Geben Sie Ihren Benutzernamen oder Ihre E-Mail ein. Bei einem passenden Konto wird ein Reset-Link an die hinterlegte E-Mail gesendet.",
            ["forgot.who"]        = "Benutzername oder E-Mail",
            ["forgot.submit"]     = "Reset-Link senden",
            ["forgot.sent"]       = "Falls das Konto existiert, wurde ein Reset-Link gesendet. Prüfen Sie Ihre E-Mail und folgen Sie dem Link innerhalb von 30 Minuten.",
            ["forgot.backToLogin"]= "Zurück zur Anmeldung",
            ["reset.title"]       = "Neues Passwort wählen",
            ["reset.prompt"]      = "Geben Sie Ihr neues Passwort ein.",
            ["reset.submit"]      = "Neues Passwort speichern",
            ["reset.error.missingToken"] = "Reset-Link fehlt oder ist ungültig. Bitte einen neuen anfordern.",
            ["reset.error.invalid"] = "Der Reset-Link ist ungültig oder abgelaufen. Bitte einen neuen anfordern.",

            // Dashboard
            ["dashboard.title"]              = "Übersicht",
            ["dashboard.stat.applications"]  = "Anwendungen",
            ["dashboard.stat.published"]     = "Veröffentlichte Versionen",
            ["dashboard.stat.downloads"]     = "Downloads gesamt",
            ["dashboard.applications"]       = "Anwendungen",
            ["dashboard.viewAll"]            = "Alle anzeigen",
            ["dashboard.col.name"]           = "Name",
            ["dashboard.col.slug"]           = "Slug",
            ["dashboard.col.latest"]         = "Neueste (Stable)",
            ["dashboard.col.releases"]       = "Versionen",
            ["dashboard.empty"]              = "Noch keine Anwendungen.",
            ["dashboard.empty.cta"]          = "Erste Anwendung registrieren",
            ["dashboard.manage"]             = "Verwalten",

            // Common
            ["common.save"]       = "Speichern",
            ["common.cancel"]     = "Abbrechen",
            ["common.delete"]     = "Löschen",
            ["common.edit"]       = "Bearbeiten",
            ["common.create"]     = "Anlegen",
            ["common.publish"]    = "Veröffentlichen",
            ["common.archive"]    = "Archivieren",
            ["common.copy"]       = "Kopieren",
            ["common.copied"]     = "Kopiert!",
            ["common.confirm"]    = "Bestätigen",
            ["common.loading"]    = "Wird geladen…",
            ["common.refresh"]    = "Aktualisieren",
            ["common.deleteYes"]  = "Ja, löschen",
            ["common.name"]       = "Name",
            ["common.description"]= "Beschreibung",
            ["common.upload"]     = "Hochladen",

            // Page titles
            ["page.settings"]     = "Einstellungen",
            ["page.security"]     = "Sicherheit",
            ["page.audit"]        = "Audit-Log",
            ["page.apps"]         = "Anwendungen",

            // Settings page (admin)
            ["settings.ciToken"]          = "CI-Upload-Token",
            ["settings.ciToken.hint"]     = "Wird in GitHub Actions als X-UpdateHub-Token-Header verwendet. Rotieren erzeugt einen neuen Token — anschließend CI-Secrets aktualisieren.",
            ["settings.reveal"]           = "Anzeigen",
            ["settings.rotate"]           = "Token rotieren",
            ["settings.rotateConfirm"]    = "Aktuellen Token rotieren und ungültig machen?",
            ["settings.rotateYes"]        = "Ja, rotieren",
            ["settings.rotatedMsg"]       = "Token rotiert — CI-Secrets mit dem neuen Wert oben aktualisieren.",
            ["settings.smtp"]             = "E-Mail (SMTP)",
            ["settings.smtp.hint"]        = "SMTP-Zugangsdaten zur Laufzeit bearbeiten — Werte werden in der Datenbank gespeichert (Passwort verschlüsselt).",
            ["settings.smtp.envHint"]     = "Aktuell werden Werte aus Umgebungsvariablen / appsettings verwendet — Formular ausfüllen, um zu überschreiben.",
            ["settings.smtp.host"]        = "Host",
            ["settings.smtp.port"]        = "Port",
            ["settings.smtp.from"]        = "Absenderadresse",
            ["settings.smtp.username"]    = "Benutzername",
            ["settings.smtp.password"]    = "Passwort",
            ["settings.smtp.password.stored"]     = "gespeichert",
            ["settings.smtp.password.placeholder"]= "leer lassen, um gespeichertes Passwort zu behalten",
            ["settings.smtp.password.willClear"]  = "Gespeichertes Passwort wird beim Speichern gelöscht.",
            ["settings.smtp.password.clear"]      = "Gespeichertes Passwort löschen",
            ["settings.smtp.to"]          = "Empfänger (To)",
            ["settings.smtp.sendTest"]    = "Test-E-Mail senden",
            ["settings.smtp.sending"]     = "Wird gesendet…",
            ["settings.smtp.saved"]       = "SMTP-Einstellungen gespeichert.",
            ["settings.smtp.testSent"]    = "Test-E-Mail in die Warteschlange gestellt (Posteingang prüfen, falls SMTP konfiguriert ist).",

            // Navigation user info
            ["nav.signedInAs"]            = "Angemeldet als",
            ["nav.user"]                  = "Benutzer",
            ["nav.role"]                  = "Rolle",
            ["nav.search"]                = "Apps suchen…",
            ["nav.analytics"]             = "Statistik",
            ["nav.storage"]               = "Speicher",
            ["dashboard.recent"]          = "Letzte Aktivität",
            ["analytics.title"]           = "Statistik",
            ["analytics.window.7"]        = "Letzte 7 Tage",
            ["analytics.window.30"]       = "Letzte 30 Tage",
            ["analytics.window.90"]       = "Letzte 90 Tage",
            ["analytics.totalDownloads"]  = "Downloads gesamt",
            ["analytics.activeDays"]      = "Aktive Tage",
            ["analytics.avgPerDay"]       = "Ø / Tag",
            ["analytics.perDay"]          = "Downloads pro Tag",
            ["analytics.byPlatform"]      = "Nach Plattform",
            ["analytics.topVersions"]     = "Top-Versionen",
            ["analytics.noData"]          = "Keine Daten für diesen Zeitraum.",
            ["storage.title"]             = "Speicher",
            ["storage.totalOnDisk"]       = "Auf der Festplatte gesamt",
            ["storage.totalInDb"]         = "Erfasste Artefakte",
            ["storage.artifactCount"]     = "Anzahl Artefakte",
            ["storage.byApp"]             = "Nach Anwendung",
            ["storage.size"]              = "Größe",
            ["storage.share"]             = "Anteil",
            ["storage.empty"]             = "Noch keine Artefakte gespeichert.",
            ["storage.cleanup"]           = "Aufräumen",
            ["storage.cleanup.hint"]      = "Löscht dauerhaft Artefakt-Dateien archivierter Versionen älter als der gewählte Zeitraum. Versionsmetadaten bleiben erhalten.",
            ["storage.cleanup.olderThan"] = "Archiviert länger als",
            ["storage.cleanup.run"]       = "Aufräumen starten",
            ["storage.days"]              = "Tage",
            ["releases.dropHint"]         = "Datei hier ablegen oder zum Auswählen klicken",
            ["users.edit"]                = "Benutzer bearbeiten",
            ["users.forceChangePw"]       = "Passwortwechsel bei nächster Anmeldung erzwingen",
            ["users.forceChangePw.self"]  = "Sie können bei Ihrem eigenen Konto keinen Passwortwechsel erzwingen.",
            ["apps.appToken.rotated"]     = "rotiert",
            ["apps.appToken.rotated.today"] = "heute",
            ["settings.webhook"]          = "Webhook-Signierung",
            ["settings.webhook.hint"]     = "Ausgehende Publish-Webhooks werden mit einem HMAC-SHA256-Header (X-UpdateHub-Signature) signiert, damit der Empfänger die Herkunft prüfen kann. Eine Rotation entwertet das vorherige Geheimnis sofort.",
            ["settings.webhook.generate"] = "Geheimnis generieren",
            ["settings.webhook.rotate"]   = "Geheimnis rotieren",
            ["settings.webhook.rotated"]  = "Webhook-Geheimnis rotiert. Aktualisieren Sie alle prüfenden Empfänger.",
            ["settings.webhook.cleared"]  = "Geheimnis gelöscht — ausgehende Webhooks werden nicht mehr signiert.",
            ["account.tokens"]            = "Persönliche Zugangstoken",
            ["account.tokens.hint"]       = "Langlebige Bearer-Tokens für CLI / Skripte, die in Ihrem Namen Artefakte hochladen. Jeder Token wird nur einmal angezeigt — sofort kopieren.",
            ["account.tokens.name"]       = "Bezeichnung",
            ["account.tokens.expiry"]     = "Läuft ab in",
            ["account.tokens.expiry.never"] = "Nie",
            ["account.tokens.create"]     = "Token erstellen",
            ["account.tokens.shown"]      = "Jetzt kopieren (nur einmal angezeigt)",
            ["account.tokens.prefix"]     = "Präfix",
            ["account.tokens.expires"]    = "Läuft ab",
            ["account.tokens.revoke"]     = "Widerrufen",
            ["account.tokens.revoked"]    = "Widerrufen",
            ["account.tokens.expired"]    = "Abgelaufen",
            ["account.sessions"]          = "Aktive Sitzungen",
            ["account.sessions.hint"]     = "Aus allen Browsern und Geräten abmelden — nützlich bei Verdacht auf Kompromittierung. Sie müssen sich hier erneut anmelden.",
            ["account.sessions.revokeAll"] = "Überall abmelden",
            ["account.sessions.revoked"]   = "Alle Sitzungen ungültig gemacht. Sie werden in Kürze abgemeldet.",
            ["account.totp.backupCodes.remaining"]    = "Verbleibende Backup-Codes",
            ["account.totp.backupCodes.regenerate"]   = "Codes neu generieren",
            ["account.totp.backupCodes.lowWarning"]   = "Es sind nur noch sehr wenige Backup-Codes übrig — neu generieren.",
            ["account.totp.backupCodes.shownOnce"]    = "Neue Backup-Codes — sicher aufbewahren",
            ["account.totp.backupCodes.shownOnce.hint"] = "Jeder Code ist einmalig nutzbar und ersetzt einen Authenticator-Code, falls Sie Ihr Gerät verlieren. Die Codes werden nicht erneut angezeigt.",
            ["apps.webhookUrl"]            = "App-spezifische Webhook-URL",
            ["apps.webhookUrl.hint"]       = "(optional — überschreibt für diese App den globalen Publish-Webhook)",
            ["settings.backup"]            = "Sicherung",
            ["settings.backup.hint"]       = "Lädt ein ZIP mit der SQLite-Datenbank und dem Data-Protection-Schlüsselring herunter. Artefakt-Dateien sind nicht enthalten — sichern Sie diese separat auf Volume-Ebene.",
            ["settings.backup.download"]   = "Sicherung herunterladen",

            // Apps list
            ["apps.new"]                  = "Neue Anwendung",
            ["apps.empty"]                = "Noch keine Anwendungen registriert.",
            ["apps.col.created"]          = "Erstellt",
            ["apps.slug"]                 = "Slug",
            ["apps.slug.hint"]            = "(eindeutige ID für API-Aufrufe, z. B. meine-app)",
            ["apps.descriptionOptional"]  = "Beschreibung (optional)",
            ["apps.err.slugRequired"]     = "Slug ist erforderlich.",
            ["apps.err.nameRequired"]     = "Name ist erforderlich.",
            ["apps.err.slugExists"]       = "Slug existiert bereits.",

            // App detail
            ["apps.delete"]               = "Anwendung löschen",
            ["apps.edit"]                 = "Anwendung bearbeiten",
            ["apps.appToken"]             = "CI-Token der Anwendung",
            ["apps.appToken.custom"]      = "Eigener Token aktiv — überschreibt den globalen",
            ["apps.appToken.global"]      = "Globaler CI-Token wird verwendet",
            ["apps.appToken.generate"]    = "Token generieren",
            ["apps.appToken.rotate"]      = "Rotieren",
            ["apps.appToken.remove"]      = "Entfernen",
            ["apps.appToken.reveal"]      = "Anzeigen",
            ["apps.appToken.hide"]        = "Verbergen",
            ["apps.apiEndpoints"]         = "API-Endpunkte",
            ["apps.releases"]             = "Versionen",
            ["apps.newRelease"]           = "Neue Version",
            ["apps.releases.empty"]       = "Noch keine Versionen.",
            ["apps.delete.confirm"]       = "Anwendung löschen?",
            ["apps.delete.warn"]          = "Damit werden die Anwendung und alle ihre Versionen und Artefakte dauerhaft gelöscht.",

            // Releases
            ["releases.version"]          = "Version",
            ["releases.channel"]          = "Kanal",
            ["releases.status"]           = "Status",
            ["releases.notes"]            = "Versionshinweise",
            ["releases.notesPlaceholder"] = "Was hat sich in dieser Version geändert…",
            ["releases.mandatory"]        = "Pflicht-Update",
            ["releases.published"]        = "Veröffentlicht",
            ["releases.artifacts"]        = "Artefakte",
            ["releases.col.platform"]     = "Plattform",
            ["releases.col.arch"]         = "Architektur",
            ["releases.col.file"]         = "Datei",
            ["releases.col.size"]         = "Größe",
            ["releases.col.signature"]    = "Signatur",
            ["releases.col.downloads"]    = "Downloads",
            ["releases.upload"]           = "Artefakt hochladen",
            ["releases.signature"]        = "Tauri Ed25519-Signatur",
            ["releases.signature.hint"]   = "(nur für Tauri-Anwendungen)",
            ["releases.signaturePlaceholder"] = "Signatur vom tauri signer einfügen…",
            ["releases.file"]             = "Datei",
            ["releases.uploading"]        = "Wird hochgeladen, bitte warten…",
            ["releases.err.version"]      = "Version ist erforderlich.",
            ["releases.delete.confirm"]   = "Version löschen?",
            ["releases.delete.warn"]      = "Alle Artefakte werden ebenfalls dauerhaft gelöscht.",
            ["releases.empty"]            = "Noch keine Artefakte hochgeladen.",
            ["releases.manage"]           = "Verwalten →",
            ["releases.status.draft"]     = "Entwurf",
            ["releases.status.published"] = "Veröffentlicht",
            ["releases.status.archived"]  = "Archiviert",
            ["releases.channel.stable"]   = "Stable",
            ["releases.channel.beta"]     = "Beta",
            ["releases.channel.alpha"]    = "Alpha",
            ["releases.mandatoryBadge"]   = "Pflicht",
            ["releases.minFromVersion"]   = "Mindestversion für Upgrade",
            ["releases.minFromVersion.hint"]  = "(optional — Clients auf einer niedrigeren Version werden über eine Zwischenversion geleitet)",
            ["releases.minFromVersion.none"]  = "beliebig",
            ["releases.minFromVersion.badge"] = "≥",

            // Security page
            ["security.blockedIps"]       = "Gesperrte IPs",
            ["security.suspiciousIps"]    = "Verdächtige IPs",
            ["security.threshold"]        = "Auto-Sperr-Schwelle",
            ["security.loginAttempts"]    = "Anmeldeversuche",
            ["security.filterIp"]         = "Nach IP filtern…",
            ["security.blockManual"]      = "+ IP manuell sperren…",
            ["security.blockThis"]        = "Diese IP sperren",
            ["security.col.ip"]           = "IP-Adresse",
            ["security.col.status"]       = "Status",
            ["security.col.failed"]       = "Fehlgeschlagen",
            ["security.col.firstSeen"]    = "Erster Versuch",
            ["security.col.lastAttempt"]  = "Letzter Versuch",
            ["security.col.unblockedAt"] = "Entsperrt am",
            ["security.col.userAgent"]    = "User Agent",
            ["security.empty"]            = "Noch keine Anmeldeversuche aufgezeichnet.",
            ["security.unblock"]          = "Entsperren",
            ["security.block"]            = "Sperren",
            ["security.removeRecord"]     = "Eintrag entfernen",
            ["security.status.blocked"]   = "Gesperrt",
            ["security.status.blocked.manual"] = "Gesperrt (manuell)",
            ["security.status.blocked.auto"]   = "Gesperrt (auto)",
            ["security.status.suspicious"]= "Verdächtig",
            ["security.status.ok"]        = "OK",
        },
    };
}
